### PR TITLE
✨ feat(npc): add elven village npcs

### PR DESCRIPTION
**Pull request by lucasvallejo1992**
This PR adds all the Elden Village NPCs without their HTML files or interactions.

**Changes:**
`data/Npcs/1-7400.json`
`data/Npcs/Spawns/spawns.json`

**Testing:**
l2 npcs

### CODE REVIEW

**Review by dkoluris — APPROVED** [review]
Awesome work @lucasvallejo1992 
Good start :)

**Comment by dkoluris** [comment]
There a a couple missing in stores, and one overlapping in the "church" first floor (don't know how else to describe this).
Whenever you get the chance, change `.writeF(1.0)   // Movement Multiplier` to `.writeF(5.0)   // Movement Multiplier` and you will be able to check around the area fast.

**Comment by lucasvallejo1992** [comment]
> There a a couple missing in stores, and one overlapping in the "church" first floor (don't know how else to describe this). Whenever you get the chance, change `.writeF(1.0) // Movement Multiplier` to `.writeF(5.0) // Movement Multiplier` and you will be able to check around the area fast.

@dkoluris Let me check again and I'll fix them. I'm working on the NPC interactions, I'll make the fix there.

**Comment by dkoluris** [comment]
@lucasvallejo1992 I have added a method to show Npcs to the connected user based on his/her position. This means, that if at some point we have far too many mobs on the datapack, the client will only receive the closest ones based on a predefined radius.

`(World.npc.spawns.filter(ob => utils.isWithinRadius(ob.fetchLocX(), ob.fetchLocY(), coords.locX, coords.locY, 2500)) ?? []).forEach((npc) => {
            session.dataSend(ServerResponse.npcInfo(npc));
        });`

If the `2500` radius brings you trouble, let me know so i can refine.

**Comment by lucasvallejo1992** [comment]
> @lucasvallejo1992 I have added a method to show Npcs to the connected user based on his/her position. This means, that if at some point we have far too many mobs on the datapack, the client will only receive the closest ones based on a predefined radius.
> 
> `(World.npc.spawns.filter(ob => utils.isWithinRadius(ob.fetchLocX(), ob.fetchLocY(), coords.locX, coords.locY, 2500)) ?? []).forEach((npc) => { session.dataSend(ServerResponse.npcInfo(npc)); });`
> 
> If the `2500` radius brings you trouble, let me know so i can refine.

@dkoluris cool! Lemme check that up! I saw you have also added the fileExist function too, that's great so I can now check the HTML that I have added. In the future, I'd think about how to organize those HTML in folders by category.

**Pull request merged**
